/** Encode a project-relative audio request without putting raw paths in the URL. */
function encodeAudioRequest(folder, relativePath) {
  const payload = Buffer.from(JSON.stringify({ folder, relativePath }), "utf8").toString("base64url");
  return `booth-audio://local/${payload}`;
}

/** Decode a URL generated by encodeAudioRequest; reject hand-written variants. */
function decodeAudioRequest(value) {
  let url;
  try {
    url = new URL(value);
  } catch {
    throw new Error("Invalid Booth Desk audio URL");
  }
  if (url.protocol !== "booth-audio:" || url.hostname !== "local") {
    throw new Error("Invalid Booth Desk audio URL");
  }
  const encoded = url.pathname.replace(/^\//u, "");
  if (!encoded || !/^[A-Za-z0-9_-]+$/u.test(encoded)) {
    throw new Error("Invalid Booth Desk audio URL payload");
  }
  let payload;
  try {
    payload = JSON.parse(Buffer.from(encoded, "base64url").toString("utf8"));
  } catch {
    throw new Error("Invalid Booth Desk audio URL payload");
  }
  if (!payload || typeof payload.folder !== "string" || typeof payload.relativePath !== "string") {
    throw new Error("Invalid Booth Desk audio URL payload");
  }
  return payload;
}

/** Parse a single HTTP byte range for a seekable local audio response. */
function parseByteRange(value, size) {
  if (typeof value !== "string" || !Number.isSafeInteger(size) || size < 0) {
    return null;
  }
  const match = value.match(/^bytes=(\d*)-(\d*)$/u);
  if (!match) {
    return null;
  }
  const startText = match[1];
  const endText = match[2];
  if (startText === "" && endText === "") {
    return null;
  }
  let start;
  let end;
  if (startText === "") {
    const suffixLength = Number(endText);
    if (!Number.isSafeInteger(suffixLength) || suffixLength <= 0) {
      return null;
    }
    start = Math.max(0, size - suffixLength);
    end = Math.max(0, size - 1);
  } else {
    start = Number(startText);
    end = endText === "" ? size - 1 : Number(endText);
    if (!Number.isSafeInteger(start) || !Number.isSafeInteger(end) || start < 0 || end < start) {
      return null;
    }
    end = Math.min(end, size - 1);
  }
  if (size === 0 || start >= size || end < start) {
    return null;
  }
  return { start, end };
}

function streamResponse(stream, status, headers) {
  return new Response(require("node:stream").Readable.toWeb(stream), { status, headers });
}

module.exports = { decodeAudioRequest, encodeAudioRequest, parseByteRange, streamResponse };
